---

name: Maven gitflow release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Only allow on main branch
        if: github.ref != 'refs/heads/main'
        run: |
          echo "This workflow is only allowed to run on the main branch" >&2
          exit 1
      - name: Check out from repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Maven gitflow release
        run: ./mvnw -B gitflow:release gitflow:release-finish -DargLine=-DreleaseMergeFFOnly
